### ISSUE TITLE
How do you form the positive or negtive pairs?

### ISSUE THREAD

**Issue by dang-qi** [switchablenorms/DeepFashion2#12]
Hi,
I have read your paper but I couldn't find how do you form the positive/negative training data pairs? Is there any strategy to select pairs for training such as positive/negative pairs quantity ratio?

**Comment by geyuying** [comment]
A clothing item from shop images and a clothing item from consumer image are positive commercial-consumer pair if they have the same style number which is greater than 0 and they are from images with the same pair id, otherwise they are negative pairs.
During training, in a batch, 8 image-level pairs are selected where one image-level pair is made up of  one image from shops and one image from consumers. In an image-level pair, two images have the same pair_id and have clothing items with the same style. In a batch, clothing items in an image-level pair with the same style construct positive pairs, otherwise they are negative pairs.
